### ISSUE TITLE
eu-north-1.layers.newrelic-external.com not found

### ISSUE THREAD

**Issue by geoffsoftledger** [newrelic/serverless-newrelic-lambda-layers#131]
Tried to deploy a sls function with the layer in eu-north-1 and got this error:

 Request Error ------------------------------------------
 
  RequestError: Error: getaddrinfo ENOTFOUND eu-north-1.layers.newrelic-external.com
      at new RequestError (/home/gostrega/github/sl_app/serverless/users/node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (/home/gostrega/github/sl_app/serverless/users/node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (/home/gostrega/github/sl_app/serverless/users/node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (/home/gostrega/github/sl_app/serverless/users/node_modules/request/request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.EventEmitter.emit (domain.js:485:12)
      at Request.onRequestError (/home/gostrega/github/sl_app/serverless/users/node_modules/request/request.js:877:8)
      at ClientRequest.emit (events.js:315:20)
      at ClientRequest.EventEmitter.emit (domain.js:485:12)
      at TLSSocket.socketErrorListener (_http_client.js:467:9)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at emitErrorNT (internal/streams/destroy.js:100:8)
      at emitErrorCloseNT (internal/streams/destroy.js:68:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

According to the documentation:
https://discuss.newrelic.com/t/lambda-troubleshooting-framework-general-knowledge-part-1/146356
eu-north-1 is supported

**Comment by mrickard** [comment]
@geoffsoftledger Thank you for the report! We'll add `eu-north-1` to the layers server api.
