### ISSUE TITLE
Error: Cannot find module '@serverless/utils/log' after 3.1 release. 

### ISSUE THREAD

**Issue by Jtramey** [newrelic/serverless-newrelic-lambda-layers#220]
Good afternoon maintainers, 

We have started seeing any serverless deploy that uses the newrelic-lambda-layers plugin fail after the latest update. 
We are working on pinning this version to the pervious version so we can get this solved on our end, but I thought id report it nonetheless. 

If it helps the stack trace is copied below.
Thanks!

```
13:38:49  + sls print --region us-east-1 --stage prod --app-version latest --client prod
13:38:50   Error ---------------------------------------------------
13:38:50    Error: Cannot find module '@serverless/utils/log'
13:38:50    Require stack:
13:38:50    - /home/jenkins-worker/workspace/{branch_name}}/node_modules/serverless-newrelic-lambda-layers/dist/index.js
13:38:50    - /usr/lib/node_modules/serverless/lib/classes/PluginManager.js
13:38:50    - /usr/lib/node_modules/serverless/lib/Serverless.js
13:38:50    - /usr/lib/node_modules/serverless/scripts/serverless.js
13:38:50    - /usr/lib/node_modules/serverless/bin/serverless.js
13:38:50        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
13:38:50        at Function.Module._load (internal/modules/cjs/loader.js:746:27)
13:38:50        at Module.require (internal/modules/cjs/loader.js:974:19)
13:38:50        at require (internal/modules/cjs/helpers.js:101:18)
13:38:50        at Object.<anonymous> (/home/jenkins-worker/workspace/{branch_name}/node_modules/serverless-newrelic-lambda-layers/dist/index.js:19:20)
13:38:50        at Module._compile (internal/modules/cjs/loader.js:1085:14)
13:38:50        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
13:38:50        at Module.load (internal/modules/cjs/loader.js:950:32)
13:38:50        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
13:38:50        at Module.require (internal/modules/cjs/loader.js:974:19)
13:38:50        at require (internal/modules/cjs/helpers.js:101:18)
13:38:50        at requireServicePlugin (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:29:12)
13:38:50        at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:170:20
13:38:50        at Array.map (<anonymous>)
13:38:50        at PluginManager.resolveServicePlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:167:8)
13:38:50        at PluginManager.loadAllPlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:153:10)
13:38:50        at Serverless.init (/usr/lib/node_modules/serverless/lib/Serverless.js:174:30)
13:38:50        at async /usr/lib/node_modules/serverless/scripts/serverless.js:374:7

13:38:50    Your Environment Information ---------------------------
13:38:50       Operating System:          linux
13:38:50       Node Version:              14.19.1
13:38:50       Framework Version:         2.35.0
13:38:50       Plugin Version:            4.6.0
13:38:50       SDK Version:               4.3.2
13:38:50       Components Version:        3.18.2

Python version 3.8
Relevant serverless config info:
custom:
  newRelic:
    apiKey: ${env:NEW_RELIC_KEY}
    accountId: ${env:NEW_RELIC_ACCOUNT_KEY}}
    enableFunctionLogs: true
```

**Comment by mrickard** [comment]
@Jtramey Thank you for reporting! It looks to me as though you're using Serverless version 2--is that right? If so, I'd recommend falling back to our plugin version 2.4.1, though we should have a fix for this shortly.

**Comment by Jtramey** [comment]
> @Jtramey Thank you for reporting! It looks to me as though you're using Serverless version 2--is that right? If so, I'd recommend falling back to our plugin version 2.4.1, though we should have a fix for this shortly.

Hey thank you for the quick response! 

We figured that would be the case. We have struggled with getting serverless to comply with pinned versions of a few plugins, but thats on Serverless, not your plugin. We will work on locking those versions in our serverless.yml in the meantime. 

Thanks again!
