### ISSUE TITLE
nodejs16.x runtime not supported

### ISSUE THREAD

**Issue by yurimorini** [newrelic/serverless-newrelic-lambda-layers#246]
Upgrading runtime to the newly supported Node 16 I receive the following errors:

```
Unable to get layer ARN for nodejs16.x in eu-west-1
URL: https://eu-west-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=nodejs16.x
TypeError: Cannot read properties of undefined (reading 'LayerVersionArn')
      at NewRelicLambdaLayerPlugin.<anonymous> (/builds/whirlpool/vtex/kitchenaid/ka-middleware-lambda-services/node_modules/serverless-newrelic-lambda-layers/dist/index.js:518:44)
      at Generator.next (<anonymous>)
      at fulfilled (/builds/whirlpool/vtex/kitchenaid/ka-middleware-lambda-services/node_modules/serverless-newrelic-lambda-layers/dist/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Seems the new runtime is not yet supported, is there a timeline for the release ?

**Comment by mrickard** [comment]
Node 16 layers were first published on May 27, and now version 3.3.0 of the plugin supports them as well.

**Comment by yurimorini** [comment]
Thanks for you feedback
