### ISSUE TITLE
ES module support

### ISSUE THREAD

**Issue by srikanth-d-1** [newrelic/serverless-newrelic-lambda-layers#263]
I am getting following error in my ES6 serverless nodejs application (node 16x),

```
Error [ERR_REQUIRE_ESM]: require() of ES Module  /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/node-fetch/src/index.js from  /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless-newrelic-lambda-layers/dist/index.js not supported.
Instead change the require of  /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/node-fetch/src/index.js in  /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless-newrelic-lambda-layers/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ( /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless-newrelic-lambda-layers/dist/index.js:13:22)
    at async Promise.all (index 0)
    at async module.exports ( /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless/lib/utils/import-module.js:9:15)
    at async PluginManager.resolveServicePlugins ( /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless/lib/classes/plugin-manager.js:198:18)
    at async PluginManager.loadAllPlugins ( /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless/lib/classes/plugin-manager.js:136:36)
    at async Serverless.init ( /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless/lib/serverless.js:141:5)
    at async  /test/workspace/test-lambda-services/jobs/test-sqs-worker/node_modules/serverless/scripts/serverless.js:591:7
```

I am using `serverless-plugin-typescript` with blow tsconfig.json

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "sourceMap": false,
    "target": "ES2022"
  },
  "include": ["src/**/*", "declarations.d.ts"],
  "exclude": ["node_modules/**/*", ".serverless/**/*", ".webpack/**/*", ".vscode/**/*"]
}
```

**Comment by srikanth-d-1** [comment]
I was using node-fetch v3 which is ESM only module & conflicting with version used in this package. I downgrade my version to 2 and it is working.

**Comment by srikanth-d-1** [comment]
```
"Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/src/index.js from /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js not supported.",
        "Instead change the require of /var/task/src/index.js in /opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js to a dynamic import() which is available in all CommonJS modules.",
        "    at Function.wrappedLoad [as _load] (/opt/nodejs/node_modules/newrelic/lib/shimmer.js:307:24)",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:37:22)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:62:50)",
        "    at _tryRequire (file:///var/runtime/index.mjs:717:14)",
        "    at async _loadUserApp (file:///var/runtime/index.mjs:721:16)",
        "    at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)",
        "    at async file:///var/runtime/index.mjs:781:15",
        "    at async file:///var/runtime/index.mjs:4:1"
```

**Comment by mrickard** [comment]
@srikanth-d-1 For now I'd recommend keeping node-fetch at the earlier version, until we can roll out a version of the agent that fully supports ESM.

**Comment by jamalmoir** [comment]
This is blocking me using new relic.

Any plans to implement this?

**Comment by mrickard** [comment]
@jamalmoir This was an enhancement we investigated, and unfortunately there's a fundamental blocker: `NODE_PATH` is not used in resolving `import` specifiers. See [the Node ESM docs](https://nodejs.org/api/esm.html#no-node_path) for this. 

The no-code-change instrumentation we have leverages AWS's layers standard for installing our agent in `/opt/nodejs` while being able to instrument dependencies in `/var/task`, finding them by using `NODE_PATH`. Without an ambient path available, the agent in `/opt/nodejs` can't find your dependencies or handler. 

While that rules out using the Lambda Layer, you can still instrument ESM Lambda functions with New Relic, by following [these instructions](https://github.com/newrelic/newrelic-lambda-layers#support-for-es-modules-nodejs).
