### ISSUE TITLE
Cannot locate handler - newrelic-lambda-wrapper. not found

### ISSUE THREAD

**Issue by sebastianmarines** [newrelic/serverless-newrelic-lambda-layers#267]
Hi, I'm trying to use this plugin in my project using version `3.3.3`, sls 3.19, and Node 16 but I get this error.

My configuration:
```yaml
custom:
  newRelic:
          accountId: ******
          apiKey: ***********************************
          enableFunctionLogs: true
```

Plugins:
```yaml
plugins:
    - serverless-newrelic-lambda-layers
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-domain-manager
```
Logs:
```
Plugins: ["serverless-newrelic-lambda-layers","serverless-plugin-typescript","serverless-offline","serverless-domain-manager"]                                
Adding NewRelic layer to api                                                                                                                                  
Warning: Function "api" already will be handled with provider.layers; skipping.                                                                               
Compiling with Typescript...                                                                                                                                  
Using local tsconfig.json - tsconfig.json                                                                                                                     
Cannot locate handler - newrelic-lambda-wrapper. not found                                                                                                    
Environment: linux, node 16.14.0, framework 3.19.0 (local) 3.18.2v (global), plugin 6.2.2, SDK 4.3.2                                                          
Credentials: Local, "default" profile                                                                                                                         
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Typescript compilation failed. Please ensure handlers exists with ext .ts or .js
    at /home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/typescript.js:71:15
    at Array.map (<anonymous>)
    at Object.extractFileNames (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/typescript.js:56:10)
    at TypeScriptPlugin.get rootFileNames [as rootFileNames] (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:102:27)
    at TypeScriptPlugin.<anonymous> (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:159:59)
    at Generator.next (<anonymous>)
    at /home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:4:12)
    at TypeScriptPlugin.compileTs (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:143:16)
    at TypeScriptPlugin.<anonymous> (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:58:28)
    at Generator.next (<anonymous>)
    at /home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:4:12)
    at before:package:createDeploymentArtifacts (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless-plugin-typescript/dist/src/index.js:57:63)
    at PluginManager.runHooks (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginManager.invoke (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/home/sebastian/Projects/stellar/menu-manager/node_modules/serverless/lib/serverless.js:174:5)
    at async /home/sebastian/Projects/stellar/menu-manager/node_modules/serverless/scripts/serverless.js:771:9
```

**Comment by mrickard** [comment]
@sebastianmarines I haven't yet been able to reproduce this, but we've been investigating. What version of Serverless are you using on your dev machine?

**Comment by sebastianmarines** [comment]
Hi @mrickard, thanks for your response. I'm using Serverless 3.18.2
```bash
$ sls --version
Framework Core: 3.18.2
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by sebastianmarines** [comment]
I found the cause of the problem, I had previously tried the DataDog plugin and the documentation states that you need to put their plugin above `serverless-plugin-typescript`. Hence, I did the same with this plugin, and that caused the error. Is it ok if I create a PR documenting the correct way of integrating this plugin with `serverless-plugin-typescript`?

**Comment by mrickard** [comment]
@sebastianmarines Thank you for digging into that! This does track with our recommendation for use with webpack as well. That's noted as an error message in our code, but it's true that it's not in the ReadMe. 

We do welcome contributions, but I'm happy to do this one.
