### ISSUE TITLE
parts.at is not a function error inside newrelic-lambda-wrapper

### ISSUE THREAD

**Issue by TioLuiso** [newrelic/serverless-newrelic-lambda-layers#272]
Hello, we are using NewRelic lambda layer for a lambda function that is developed in NodeJS 14.x

We are using the serverless framework, so naturally, to deploy it, we used `serverless-newrelic-lambda-layers` plugin

In the past, it has worked flawlessly. However, when we tried to deploy it today, when we executed the function, we saw an error in the Cloudwatch log:

```
{
  "aws.lambda_request_id": "XXX",
  "faas.arn": "",
  "faas.execution": "XXX",
  "faas.name": "XXX",
  "index": 35,
  "message": "2022-09-01T06:52:48.357Z\tundefined\tERROR\tUncaught Exception \t{\"errorType\":\"TypeError\",\"errorMessage\":\"parts.at is not a function\",\"stack\":[\"TypeError: parts.at is not a function\",\"    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:32:31)\",\"    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:63:50)\",\"    at Module._compile (internal/modules/cjs/loader.js:1085:14)\",\"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\",\"    at Module.load (internal/modules/cjs/loader.js:950:32)\",\"    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\",\"    at Module.require (internal/modules/cjs/loader.js:974:19)\",\"    at require (internal/modules/cjs/helpers.js:101:18)\",\"    at _tryRequire (/var/runtime/UserFunction.js:194:10)\",\"    at _loadUserApp (/var/runtime/UserFunction.js:215:12)\",\"    at Object.module.exports.load (/var/runtime/UserFunction.js:279:17)\",\"    at Object.<anonymous> (/var/runtime/index.js:43:34)\",\"    at Module._compile (internal/modules/cjs/loader.js:1085:14)\",\"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\",\"    at Module.load (internal/modules/cjs/loader.js:950:32)\",\"    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\",\"    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)\",\"    at internal/main/run_main_module.js:17:47\"]}\n",
  "newrelic.logPattern": "nr.DID_NOT_MATCH",
  "newrelic.source": "api.logs",
  "plugin": "newrelic-lambda-extension:2.3.3",
  "timestamp": 1662015168370,
  "trace.id": ""
}
```

The newRelic configuration that we have in `serverless.ts` is

```
newRelic: {
      accountId: "${env:NEW_RELIC_ACCOUNT_KEY}",
      apiKey: "${env:NEW_RELIC_API_KEY}",
      enableFunctionLogs: true
    },
```

The lambda layer that was selected by the plugin is `arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS14X:67`. Then we specified the layerArn `arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS14X:66`

And now it works

**Comment by strelov1** [comment]
Have the same issue

**Comment by RishikeshDarandale** [comment]
Any update on this one?

**Comment by jeff-pal** [comment]
Was this issue fixed? I'still having this error:

```
undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "parts.at is not a function",
    "stack": [
        "TypeError: parts.at is not a function",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:32:31)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:63:50)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:194:10)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:215:12)"
    ]
}
```

**Comment by mrickard** [comment]
@jeff-pal It should be fixed with the latest layer version. What's the ARN of the current layer you're using? There should be a newer version than that, if you check https://layers.newrelic-external.com/

**Comment by Zeikko** [comment]
@mrickard do you have any advice how to prevent similar issues in the future? This took a service that i'm managing offline in production. I would like to change our solution so that even if the newrelic lambda layer is not working our app would still run without logging.

Or alternative is there a way for us to roll out the layer updates in more controlled way. Currently the lambda layer update is not in our control and things can break unexpectedly.

I admit that we did not understand the implications of adding this lambda layer into our service and we need to study and re-evaluate if this is something we want to keep doing now that we understand that the lambda layer creates a new supply chain vulnerability for our service.

**Comment by Zeikko** [comment]
We have now explicitly defined the `layerArn` to prevent similar issues in the future. I hope this helps and doesn't cause new issues.

**Comment by mrickard** [comment]
@Zeikko Explicitly defining the layerArn is indeed the best way to guarantee that your function won't be affected by any changes.

**Comment by RishikeshDarandale** [comment]
Today `sls deploy` is failing with below error. Is this related?

```
Environment: linux, node 14.20.0, framework 3.16.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read property 'filter' of null
    at Integration.<anonymous> (/my/projects//node_modules/serverless-newrelic-lambda-layers/dist/integration.js:33:42)
    at Generator.next (<anonymous>)
    at fulfilled (/my/projects//node_modules/serverless-newrelic-lambda-layers/dist/integration.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by liuxiaofeng1981** [comment]
Couldn't agree more with @Zeikko as similarly this brought down our entire production site!

We also fixed it by explicitly define `layerArn`.
