### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by skhaz** [newrelic/serverless-newrelic-lambda-layers#384]
I'm having several errors while trying to use this library:

First error:

```
✖ Error while creating the New Relic AWS Lambda cloud integration: Error: ["data.cloudLinkAccount missing in response"].
```

Then several errors:
```
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process

✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet 

[NewRelicLogIngestion-CREATE-1695671591203].
      at /opt/workspace/project/project-ingestion-layer/node_modules/serverless/lib/aws/request.js:221:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (/opt/workspace/project/project-ingestion-layer/node_modules/serverless/lib/aws/request.js:145:14)
    code: 'AWS_CLOUD_FORMATION_CREATE_CHANGE_SET_VALIDATION_ERROR',
    decoratedMessage: undefined,
    providerError:
     { Error [ValidationError]: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-1695671591203].
         at Request.extractError (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/protocol/query.js:50:29)
         at Request.callListeners (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
         at Request.emit (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at Request.emit (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at callNextListener (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
         at IncomingMessage.onEnd (/opt/workspace/project/project-ingestion-layer/node_modules/aws-sdk/lib/event_listeners.js:417:13)
         at IncomingMessage.emit (node:events:525:35)
         at IncomingMessage.emit (node:domain:489:12)
         at endReadableNT (node:internal/streams/readable:1359:12)
         at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
       code: 'ValidationError',
       time: 2023-09-25T19:53:15.363Z,
       requestId: 'b6a54993-9985-47d7-a5fe-64f4654e3fab',
       statusCode: 400,
       retryable: false,
       retryDelay: 44.92239359967161 },
    providerErrorCodeExtension: 'VALIDATION_ERROR' }
```

My setup is simple:

```
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-newrelic-lambda-layers
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    includeModules: true
  newRelic:
    debug: true
    accountId: '1234'
    apiKey: 'F...BAA'
    enableExtension: true
    enableIntegration: true
    logEnabled: true
```

What I'm doing wrong?

**Comment by mrickard** [comment]
@skhaz Bypass that check by removing the `enableIntegration: true` from your variables. You seem already to have the integration.

**Comment by mrickard** [comment]
@skhaz Are you authenticated to AWS in your shell when you try to deploy? `Unable to get stack information` suggests that Serverless might not have read access to your account. What happens if you try deploying with this plugin *not* enabled (removed from the plugins list). If that deployment is successful, then you're likely properly authenticated to AWS. 

If that's successful, then re-enable this plugin and try reordering your plugins list so that this plugin is listed last. 

Failing that, I'd recommend opening a ticket with https://support.newrelic.com/

**Comment by skhaz** [comment]
@mrickard, I ran this command before the deployment

```
export AWS_ACCESS_KEY_ID=AKIA... && export AWS_SECRET_ACCESS_KEY=sa3qln...
```

Is this suffice, or do I need the `aws-cli` installed and configured?

**Comment by skhaz** [comment]
@mrickard, you're right, the problem was the plugin order

```
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-newrelic-lambda-layers
  - serverless-iam-roles-per-function
  - serverless-offline
```

Thank you so much!

**Comment by mrickard** [comment]
@skhaz Glad to help! Typically we recommend that this plugin is listed last, though apparently `serverless-iam-roles-per-function` and  `serverless-offline` can follow it.
