### ISSUE TITLE
Support for newrelic-log-ingestion-0356e24a3f87 naming format

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/serverless-newrelic-lambda-layers#402]
#### Description

After resolving a previous issue with an old CloudFormation stack, the `serverless-newrelic-lambda-layers` plugin successfully creates a `NewRelicLogIngestion` CloudFormation stack. However, the Serverless Framework deployment still fails, reporting that it cannot find the `newrelic-log-ingestion` function and incorrectly validating the changeSet.

#### Steps to Reproduce

1. Delete any existing CloudFormation stacks that might conflict with the New Relic setup.
2. Run `sls deploy --verbose` to deploy the serverless application with the `serverless-newrelic-lambda-layers` plugin.

#### Expected Behavior

The Serverless Framework should recognize the successfully created `NewRelicLogIngestion` CloudFormation stack and complete the deployment without errors.

#### Actual Behavior

The Serverless Framework deployment fails with the following error:

```sh
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion
creating required newrelic-log-ingestion function in region us-west-2
✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-1234567891234].
```

The error suggests that the Serverless Framework is attempting to validate a changeSet that is different from the one actually created by the CloudFormation stack.

#### Additional Information

- **Serverless Framework Version**: 3.38.0
- **Serverless-NewRelic-Lambda-Layers Plugin Version**: 5.0.0
- **NewRelic-Lambda-CLI Version**: 0.8.0
- **Operating System**: Linux
- **Stack Trace**:

```sh
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion
creating required newrelic-log-ingestion function in region us-west-2
✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
      at /home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:221:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (/home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:145:14)
    code: 'AWS_CLOUD_FORMATION_CREATE_CHANGE_SET_VALIDATION_ERROR',
    decoratedMessage: undefined,
    providerError:
     { Error [ValidationError]: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
         at Request.extractError (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/protocol/query.js:50:29)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at callNextListener (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
         at IncomingMessage.onEnd (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/event_listeners.js:417:13)
         at IncomingMessage.emit (node:events:531:35)
         at IncomingMessage.emit (node:domain:488:12)
         at endReadableNT (node:internal/streams/readable:1696:12)
         at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
       code: 'ValidationError',
       time: 2024-01-20T03:52:57.928Z,
       requestId: '25aa44bd-494b-4344-b43b-b50ab62e06c3',
       statusCode: 400,
       retryable: false,
       retryDelay: 59.42190121235369 },
    providerErrorCodeExtension: 'VALIDATION_ERROR' }
```

#### Possible Solution

The `serverless-newrelic-lambda-layers` plugin may need to be updated to correctly validate the existing CloudFormation stack and its changeSet, or to properly handle the case where the `NewRelicLogIngestion` stack has already been created. Additionally, ensuring that the plugin can find the `newrelic-log-ingestion` function after it has been created might resolve the error.

#### Notes

It's looking to validate a changeSet like `NewRelicLogIngestion-CREATE-123456789123`, but the actual changeSet that was created successfully has a different series of digits on the end.

**Comment by keegoid-nr** [comment]
### Serverless Framework Deployment Fails Despite Successful NewRelicLogIngestion Stack Creation

#### Description

After resolving a previous issue with an old CloudFormation stack, the `serverless-newrelic-lambda-layers` plugin successfully creates a `NewRelicLogIngestion` CloudFormation stack. However, the Serverless Framework deployment still fails, reporting that it cannot find the `newrelic-log-ingestion` function and incorrectly validating the changeSet.

#### Steps to Reproduce

1. Delete any existing CloudFormation stacks that might conflict with the New Relic setup.
2. Run `sls deploy --verbose` to deploy the serverless application with the `serverless-newrelic-lambda-layers` plugin.

#### Expected Behavior

The Serverless Framework should recognize the successfully created `NewRelicLogIngestion` CloudFormation stack and complete the deployment without errors.

#### Actual Behavior

The Serverless Framework deployment fails with the following output:

```sh
✖ Could not find a newrelic-log-ingestion function installed.
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion ...
✖ Unable to get stack information. ✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-1234567891234]. ... (additional error output) }
Warning: Unable to create newrelic-log-ingestion function. Please verify that required environment variables have been set.
```


The error suggests that the Serverless Framework is attempting to validate a changeSet that is different from the one actually created by the CloudFormation stack.

#### Additional Information

**Stack Trace**:

```sh
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion
creating required newrelic-log-ingestion function in region us-west-2
✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
      at /home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:221:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (/home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:145:14)
    code: 'AWS_CLOUD_FORMATION_CREATE_CHANGE_SET_VALIDATION_ERROR',
    decoratedMessage: undefined,
    providerError:
     { Error [ValidationError]: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
         at Request.extractError (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/protocol/query.js:50:29)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at callNextListener (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
         at IncomingMessage.onEnd (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/event_listeners.js:417:13)
         at IncomingMessage.emit (node:events:531:35)
         at IncomingMessage.emit (node:domain:488:12)
         at endReadableNT (node:internal/streams/readable:1696:12)
         at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
       code: 'ValidationError',
       time: 2024-01-20T03:52:57.928Z,
       requestId: '25aa44bd-494b-4344-b43b-b50ab62e06c3',
       statusCode: 400,
       retryable: false,
       retryDelay: 59.42190121235369 },
    providerErrorCodeExtension: 'VALIDATION_ERROR' }
```

#### Possible Solution

The `serverless-newrelic-lambda-layers` plugin may need to be updated to correctly validate the existing CloudFormation stack and its changeSet, or to properly handle the case where the `NewRelicLogIngestion` stack has already been created. Additionally, ensuring that the plugin can find the `newrelic-log-ingestion` function after it has been created might resolve the error.

#### Notes

It's looking to validate a changeSet like `NewRelicLogIngestion-CREATE-123456789123`, but the actual changeSet that was created successfully has a different series of digits on the end.

**Comment by mrickard** [comment]
@keegoid-nr This is in the release pipeline with v5.0.1. Thank you for reporting!
