### ISSUE TITLE
Deploying on serverless causes error with fetch not defined

### ISSUE THREAD

**Issue by svarughese91** [newrelic/serverless-newrelic-lambda-layers#71]
So I am following this doc: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-serverless-monitoring-aws-lambda#connect-aws. So I can turn on monitoring for my lambda function.  I follow all the instructions and for  Enable Lambda instrumentation step 3 i use option 1 for the serverless plugin.  I follow the instructions and then when i go to deploy i get the error: 
		Serverless: WARNING: Function api has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
 
```
		  Reference Error ----------------------------------------
 
		  ReferenceError: fetch is not defined
		      at /home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/api.js:16:17
		      at Generator.next (<anonymous>)
		      at /home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/api.js:8:71
		      at new Promise (<anonymous>)
		      at __awaiter (/home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/api.js:4:12)
		      at Object.exports.nerdgraphFetch (/home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/api.js:12:53)
		      at NewRelicLambdaLayerPlugin.<anonymous> (/home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/integration.js:26:49)
			  at Generator.next (<anonymous>)
			       at /home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/integration.js:8:71
			       at new Promise (<anonymous>)
			       at __awaiter (/home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/integration.js:4:12)
			       at NewRelicLambdaLayerPlugin.check (/home/runner/work/microservice_repair/microservice_repair/node_modules/serverless-newrelic-lambda-layers/dist/integration.js:23:16)
			       at BbPromise.reduce (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55)
			   From previous event:
			       at PluginManager.invoke (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
			       at getHooks.reduce.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:533:24)
			   From previous event:
			       at PluginManager.run (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:533:8)
			       at variables.populateService.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/Serverless.js:168:33)
			   From previous event:
			       at Serverless.run (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/Serverless.js:155:74)
			       at serverless.init.then.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/scripts/serverless.js:50:26)
			       at runCallback (timers.js:705:18)
			       at tryOnImmediate (timers.js:676:5)
			       at processImmediate (timers.js:658:5)
			       at process.topLevelDomainCallback (domain.js:126:23)
			   From previous event:
			   at Object.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/scripts/serverless.js:50:4)
			        at Module._compile (internal/modules/cjs/loader.js:778:30)
			        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
			        at Module.load (internal/modules/cjs/loader.js:653:32)
			        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
			        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
			        at Module.require (internal/modules/cjs/loader.js:692:17)
			        at require (internal/modules/cjs/helpers.js:25:18)
			        at Object.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/bin/serverless.js:47:1)
			        at Module._compile (internal/modules/cjs/loader.js:778:30)
			        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
			        at Module.load (internal/modules/cjs/loader.js:653:32)
			        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
			        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
			        at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
			        at startup (internal/bootstrap/node.js:283:19)
			        at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Tried older version but still same error.  Any thoughts on what I am missing?

**Comment by kolanos** [comment]
@svarughese91 Thanks for reporting. Are you getting this error with `v0.1.x`?

**Comment by svarughese91** [comment]
v0.2.2

**Comment by kolanos** [comment]
@svarughese91 Please  upgrade to `v0.2.3` and let us know if you continue to see errors. Thanks again.
